export interface staffinfo{
    status:string,
    branch_code:string,
    staff_id:string,
    full_name:string,
    position_id:string,
    position:string,
    phone:string,
    gender:string,
    address:string,
    google_map:string,
    address_code:string,
    remark:string,
    inputter:string,
    DOB:string,
    active?:boolean,
    is_update?:boolean,
}